dist: xenial

language: php

php:
  - '7.1'

before_script:
  - composer install

script:
  - ./vendor/bin/phpmd ./ --exclude vendor text Tests/phpmd.xml
  - ./vendor/bin/phpcs -pvs --ignore=vendor --report=full --standard=Tests/phpcs.xml ./
